// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMPLiSPjocFF75HingUTkuKX9F3feH2WM',
    appId: '1:235982705851:web:7a2b6c1d92fad6ec94459e',
    messagingSenderId: '235982705851',
    projectId: 'fcm-demo-7875e',
    authDomain: 'fcm-demo-7875e.firebaseapp.com',
    storageBucket: 'fcm-demo-7875e.firebasestorage.app',
    measurementId: 'G-K0VW66JGP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwbDeyS_2g5JAE7F5oY-HZXHey--8ra3w',
    appId: '1:235982705851:android:7853c3fbc37f096894459e',
    messagingSenderId: '235982705851',
    projectId: 'fcm-demo-7875e',
    storageBucket: 'fcm-demo-7875e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMPLiSPjocFF75HingUTkuKX9F3feH2WM',
    appId: '1:235982705851:web:54b84f8f6d263d3894459e',
    messagingSenderId: '235982705851',
    projectId: 'fcm-demo-7875e',
    authDomain: 'fcm-demo-7875e.firebaseapp.com',
    storageBucket: 'fcm-demo-7875e.firebasestorage.app',
    measurementId: 'G-8GXZHC2595',
  );
}
